spring:
  datasource:
    url: ${DB_URL}
    username: root
    password: ${MYSQL_PASSWD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update # Application 실행시 DB 초기화하지 않고 기존 저장되어 있던 DB를 사용
        format_sql: true
    defer-datasource-initialization: true
    profiles:
      include: create
  redis:
    port: 6379
    host: localhost
#    password:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 663642..
#            client-secret: GOCSP...
#            scope:
#              - email
#              - profile
jwt:
  issuer: test@example.com
  secret_key: study-springboot